version: '3.4'

services:
  bowling.application.painelonblazor:
    image: ${DOCKER_REGISTRY-}bowlingapplicationpainelonblazor
    container_name: painel
    build:
      context: .
      dockerfile: Bowling.Application.PainelOnBlazor/Dockerfile
    environment:
      NMSCONFIGURATIONS_URI: activemq:tcp://activemq:61616?wireFormat.tightEncodingEnabled=true
      NMSCONFIGURATIONS_USERNAME: user-amq
      NMSCONFIGURATIONS_PASSWORD: password-amq

  bowling.application.playworkerservice:
    image: ${DOCKER_REGISTRY-}bowlingapplicationplayworkerservice
    container_name: player
    build:
      context: .
      dockerfile: Bowling.Application.PlayWorkerService/Dockerfile
    environment:
      NMSCONFIGURATIONS_URI: activemq:tcp://activemq:61616?wireFormat.tightEncodingEnabled=true
      NMSCONFIGURATIONS_USERNAME: user-amq
      NMSCONFIGURATIONS_PASSWORD: password-amq
      BOWLING_DELAY : 1000
      BOWLING_PLAYENAME: Maria
      BOWLING_ALLEY: "Worker Test"

  activemq:
    image: vromero/activemq-artemis:latest-alpine
    container_name: activemq
    environment:
      ARTEMIS_USERNAME: user-amq
      ARTEMIS_PASSWORD: password-amq
    ports:
      - 61616:61616

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: