name: Analyze pull request

on:
#   pull_request:
#     types: [opened, edited, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: 3.1.100
      - name: Sonarscanner for dotnet
        uses: Secbyte/dotnet-sonarscanner@v2.2
        with:
          buildCommand: dotnet build Bowling.sln
          testCommand: dotnet test Bowling.sln
          projectKey: ervinnotari_Bowling
          projectName: Bowling
          sonarOrganisation: ${{ secrets.SONAR_ORGANIZATION }}
          beginArguments: >
              /d:sonar.verbose="true"
              /d:sonar.cs.opencover.reportsPaths='"/path/to/coverage.xml","/path/to/coverage.2.xml"'
              /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

