name: CI for Bowling in .NET Core

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    name: CI plan for Bowling
    strategy:
      matrix:
        os: [ubuntu-latest] #, macOS-latest, windows-latest
    steps:
#    - uses: actions/checkout@v2
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1.4.0
#      with:
#        dotnet-version: 3.1.100
#    - name: Build Bowling
#      run: dotnet build Bowling.sln --configuration Release 
#    - name: Test Bowling
#      run: dotnet test Bowling.sln --configuration Release

     #- name: Deploy to Heroku
       #env:
       #  HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
       #  HEROKU_APP_NAME: "bowling-painel-on-blazor"
       #if: github.ref == 'refs/heads/master' && job.status == 'success'
       #run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
       
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login 
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: "bowling-painel-on-blazor"
      run: heroku container:push -a $HEROKU_APP_NAME web 
    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: "bowling-painel-on-blazor"
      run: heroku container:release -a $HEROKU_APP_NAME web 
