name: Analyze pull request

on:
  #pull_request:
  push:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: 3.1.100
      - name: Sonarscanner for dotnet
        uses: Secbyte/dotnet-sonarscanner@v2.2
        with:
          buildCommand: dotnet build Bowling.sln
          testCommand: dotnet test Bowling.sln
          projectKey: ervinnotari_Bowling
          projectName: Bowling
          sonarOrganisation: ${{ secrets.SONAR_ORGANIZATION }}
          beginArguments: >
              /d:sonar.verbose="true"
              /d:sonar.cs.opencover.reportsPaths='"/path/to/coverage.xml","/path/to/coverage.2.xml"'
              /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
              /d:sonar.pullrequest.key=${{ github.event.number }}
              /d:sonar.pullrequest.branch=${{ github.HEAD_REF }}
              /d:sonar.pullrequest.base=${{ github.BASE_REF }}
              /d:sonar.pullrequest.github.repository=${{ github.repository }}
              /d:sonar.scm.provider=git
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

