name: Deploy

on:
  push:
    branches:
      - heroku
  schedule:
    - cron: "0 12 * * 5"

jobs:
  sync-branch:
    if: github.event.pull_request.merged != 'true'
    name: "Branch Merge"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: master -> heroku
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: heroku
          github_token: ${{ secrets.GITHUB_TOKEN }}

  panel-heroku-deploy:
    runs-on: ubuntu-latest
    name: "Painel: Heroku"
    needs: [sync-branch]
    steps: 

      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.7.2
      - name: Process begin
        run: |
          dotnet restore Bowling.sln
          dotnet build Bowling.sln -c Release --no-restore

      - name: Heroku container publish
        if: success()
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{'bowling-painel-on-blazor'}}
        run: |
          docker build -t painel:lasted -f Bowling.Application.PainelOnBlazor/Dockerfile.heroku .
          heroku container:login
          docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
          docker tag painel:lasted registry.heroku.com/bowling-painel-on-blazor/web
          docker push registry.heroku.com/bowling-painel-on-blazor/web
          heroku container:release web -a bowling-painel-on-blazor

  panel-dockerhub-deploy:
    runs-on: ubuntu-latest
    name: "Painel: Docker Hub"
    needs: [sync-branch]
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.7.2
      - name: Process begin
        run: |
          dotnet restore Bowling.sln
          dotnet build Bowling.sln -c Release --no-restore

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_KEY }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Bowling.Application.PainelOnBlazor/Dockerfile
          push: true
          tags: ervinnotari/bowling:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
