name: Heroku Scheduler 

on:
  schedule:
    - cron: "*/6 * * * *" #'0 12 * * 5'

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> heroku
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: heroku
          github_token: ${{ secrets.GITHUB_TOKEN }}
