name: SonarCloud Actions

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: ["**"]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: build and test
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="..\coverage.xml"
    - uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=gtmaster-github
          -Dsonar.projectKey=SiGamePackOptimizer
          -Dsonar.cs.opencover.reportsPaths="coverage.xml"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}