name: .NET

on:
  push:
    branches: [ master ]
    
jobs:
  panel-dockerhub-deploy:
    runs-on: ubuntu-latest
    name: "Painel Automated Docker Hub publish"
    steps: 
    
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_KEY }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Bowling.Application.PainelOnBlazor/Dockerfile
          push: true
          tags: ervinnotari/bowling:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
